In [1]:
import pandas as pd
from pathlib import Path

In [4]:
# read all csv with "combined" in the name
csv_files = Path('.').glob('*combined*.csv')
csv_files = [str(x) for x in csv_files]
csv_files

['combined_metrics_finished_edges.csv',
 'combined_metrics_finished_paths.csv',
 'combined_metrics_unfinished_edges.csv',
 'combined_metrics_unfinished_paths.csv']

In [8]:
dfs = {x: pd.read_csv(x) for x in csv_files}
for name, df in dfs.items():
    print(name)
    display(df)
    print(df.columns)

combined_metrics_finished_edges.csv

,Unnamed: 0,edge,mean_bert_score,mean_rating
0,0,"('Slavery', 'United_States')",0.193962,3.000000
1,1,"('Life', 'Organism')",0.313079,3.363636
2,2,"('Mercury_%28planet%29', 'Venus')",0.508045,2.000000
3,3,"('12th_century', '2nd_century')",0.824299,2.000000
4,4,"('J._R._R._Tolkien', 'Roman_Catholic_Church')",0.111871,1.000000
...,...,...,...,...
60180,60180,"('Ancient_Greece', 'Poetry')",0.196153,2.000000
60181,60181,"('World_War_II', 'NATO')",0.380185,1.000000
60182,60182,"('Liberalism', 'Latin')",0.253353,NaN
60183,60183,"('Troop_sleeper', 'Refrigerator_car')",0.366437,NaN
60184,60184,"('Bolivia', 'Country')",0.524087,2.000000

Index(['Unnamed: 0', 'edge', 'mean_bert_score', 'mean_rating'], dtype='object')
combined_metrics_finished_paths.csv

,Unnamed: 0,hashedIpAddress,timestamp,durationInSec,path,rating,link_position,path_length,optimal_path_length,coarse_mean_time,...,path_degree_slope_before,path_degree_slope_after,path_clustering_slope_before,path_clustering_slope_after,path_degree_centrality_slope_before,path_degree_centrality_slope_after,path_betweenness_slope_before,path_betweenness_slope_after,path_closeness_slope_before,path_closeness_slope_after
0,0,6a3701d319fc3754,2011-02-15 03:26:49,166,"['14th_century', '15th_century', '16th_century...",NaN,214.0,9,3.0,18.444444,...,8.571429,-42.0,0.011691,0.054550,0.001867,-0.009148,0.000526,-0.000400,0.000736,-0.055022
1,1,3824310e536af032,2012-08-12 06:36:52,88,"['14th_century', 'Europe', 'Africa', 'Atlantic...",3.0,214.0,5,3.0,17.600000,...,NaN,-329.0,NaN,0.075132,NaN,-0.071662,NaN,-0.012097,NaN,-0.097114
2,2,415612e93584d30e,2012-10-03 21:10:40,138,"['14th_century', 'Niger', 'Nigeria', 'British_...",NaN,10681.0,8,3.0,17.250000,...,39.800000,-42.0,-0.026961,0.054550,0.008669,-0.009148,0.000654,-0.000400,0.012319,-0.055022
3,3,64dd5cd342e3780c,2010-02-08 07:25:25,37,"['14th_century', 'Renaissance', 'Ancient_Greec...",NaN,131.0,4,2.0,9.250000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,015245d773376aab,2013-04-23 15:27:08,175,"['14th_century', 'Italy', 'Roman_Catholic_Chur...",3.0,19666.0,7,3.0,25.000000,...,NaN,-19.4,NaN,0.006470,NaN,-0.004226,NaN,-0.000219,NaN,-0.007018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51302,51302,15a13a1d66ef5456,2012-10-03 02:23:35,66,"['Yagan', 'Ancient_Egypt', 'Civilization']",NaN,3353.0,3,2.0,22.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51303,51303,2ef7ac844cefda58,2011-03-16 05:42:18,165,"['Yagan', 'Folklore', 'Brothers_Grimm', '19th_...",3.0,2259.0,8,3.0,20.625000,...,-3.000000,6.5,0.051676,-0.020350,-0.000653,0.001416,0.000002,-0.000109,0.052335,-0.005320
51304,51304,12863abb7887f890,2013-11-22 04:42:52,228,"['Yagan', 'Australia', 'England', 'France', 'U...",NaN,1958.0,7,3.0,32.571429,...,334.600000,-92.0,-0.029166,0.360789,0.072882,-0.020039,0.005587,-0.003235,0.085981,-0.107762
51305,51305,19f8284371753362,2011-02-27 07:42:47,56,"['Yarralumla%2C_Australian_Capital_Territory',...",1.0,9444.0,4,2.0,14.000000,...,608.000000,NaN,-0.222287,NaN,0.132433,NaN,0.012525,NaN,0.237505,NaN
51306,51306,24b84602179de377,2011-10-09 01:11:41,30,"['Ziad_Jarrah', 'Germany', 'Jew']",NaN,26220.0,3,2.0,10.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Index(['Unnamed: 0', 'hashedIpAddress', 'timestamp', 'durationInSec', 'path',
       'rating', 'link_position', 'path_length', 'optimal_path_length',
       'coarse_mean_time', 'sucessive_pairs', 'sucessive_pairs_encoded',
       'BERTscore', 'backtrack', 'numberOfPath', 'path_degree_slope_before',
       'path_degree_slope_after', 'path_clustering_slope_before',
       'path_clustering_slope_after', 'path_degree_centrality_slope_before',
       'path_degree_centrality_slope_after', 'path_betweenness_slope_before',
       'path_betweenness_slope_after', 'path_closeness_slope_before',
       'path_closeness_slope_after'],
      dtype='object')
combined_metrics_unfinished_edges.csv

,Unnamed: 0,edge,mean_bert_score
0,0,"('Slavery', 'United_States')",0.193962
1,1,"('Life', 'Organism')",0.313079
2,2,"('Nuclear_fission', 'Energy')",0.304690
3,3,"('Biology', 'Bacteria')",0.469247
4,4,"('Scottish_Gaelic_language', '19th_century')",0.217714
...,...,...,...
35413,35413,"('Ancient_Greece', 'Poetry')",0.196153
35414,35414,"('Iran', 'Art')",0.252562
35415,35415,"('Trinidad_and_Tobago', 'China')",0.294111
35416,35416,"('Troop_sleeper', 'Refrigerator_car')",0.366437
35417,35417,"('Bolivia', 'Country')",0.524087

Index(['Unnamed: 0', 'edge', 'mean_bert_score'], dtype='object')
combined_metrics_unfinished_paths.csv

,Unnamed: 0,hashedIpAddress,timestamp,durationInSec,path,target,type,link_position,path_length,optimal_path_length,...,path_degree_slope_before,path_degree_slope_after,path_clustering_slope_before,path_clustering_slope_after,path_degree_centrality_slope_before,path_degree_centrality_slope_after,path_betweenness_slope_before,path_betweenness_slope_after,path_closeness_slope_before,path_closeness_slope_after
0,0,2b015fb8181c48f2,2011-02-07 15:00:19,1818,"['Malawi', 'Democracy', 'Alexander_the_Great']",First_Crusade,timeout,5344.0,3,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,53a53bc244e08a6a,2011-02-07 17:18:25,1808,"['Paraguay', 'Bolivia']",Mount_St._Helens,timeout,582.0,2,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,131600803df4895e,2011-02-07 17:42:37,2009,"['Agriculture', 'History_of_the_world', 'China...",Grand_Canal_of_China,timeout,4741.0,4,3.0,...,-144.0,NaN,0.066452,NaN,-0.031366,NaN,-0.004739,NaN,-0.136704,NaN
3,3,486bb79910fe9dd2,2011-02-07 18:01:00,1932,"['Mind', 'Christianity', 'Europe', 'Renaissanc...",Scouting,timeout,24744.0,7,4.0,...,352.0,90.8,-0.092775,-0.006180,0.076672,0.019778,0.003044,0.001783,0.134805,0.013284
4,4,6d136e371e42474f,2011-02-07 18:07:50,175,"['4-2-0', 'United_States', 'Agriculture', 'Sug...",Cane_Toad,restart,80.0,5,5.0,...,NaN,175.5,NaN,-0.009101,NaN,0.038227,NaN,0.003802,NaN,0.014981
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19639,19639,109ed71f571d86e9,2014-01-15 12:00:12,182,"['Turks_and_Caicos_Islands', 'United_States', ...",Iraq_War,restart,45151.0,6,3.0,...,NaN,-61.4,NaN,-0.012695,NaN,-0.013374,NaN,-0.000508,NaN,-0.016099
19640,19640,109ed71f571d86e9,2014-01-15 12:06:45,180,"['Franz_Kafka', 'Tuberculosis', 'World_Health_...",Cholera,restart,174.0,7,3.0,...,16.5,-13.0,-0.008689,0.029832,0.003594,-0.002832,-0.000028,-0.000195,0.007270,0.028508
19641,19641,2e09a7224600a7cd,2014-01-15 15:06:40,1900,"['Computer_programming', 'Linguistics', 'Cultu...",The_Beatles,timeout,8682.0,4,3.0,...,41.0,NaN,-0.053902,NaN,0.008931,NaN,0.000361,NaN,0.088251,NaN
19642,19642,60af9e2138051b96,2014-01-15 15:24:41,1903,"['Jamaica', 'United_Kingdom', 'World_War_II', ...",Alan_Turing,timeout,25449.0,4,3.0,...,NaN,-843.0,NaN,0.256437,NaN,-0.183620,NaN,-0.015222,NaN,-0.178428
19643,19643,1cf0cbb3281049ab,2014-01-15 21:54:01,352,"['Mark_Antony', 'Rome', 'Tennis', 'Hawk-Eye', ...",Feather,restart,15146.0,5,3.0,...,NaN,2.0,NaN,-0.037150,NaN,0.000436,NaN,0.001500,NaN,-0.002341

Index(['Unnamed: 0', 'hashedIpAddress', 'timestamp', 'durationInSec', 'path',
       'target', 'type', 'link_position', 'path_length', 'optimal_path_length',
       'coarse_mean_time', 'sucessive_pairs', 'sucessive_pairs_encoded',
       'BERTscore', 'backtrack', 'numberOfPath', 'path_degree_slope_before',
       'path_degree_slope_after', 'path_clustering_slope_before',
       'path_clustering_slope_after', 'path_degree_centrality_slope_before',
       'path_degree_centrality_slope_after', 'path_betweenness_slope_before',
       'path_betweenness_slope_after', 'path_closeness_slope_before',
       'path_closeness_slope_after'],
      dtype='object')